Repository kubernetes-sigs/windows-operational-readiness, pull requests merged in 2023-11, with the labels that each got.

#96 Add instrunctions to specify why and how to implement mutating webhook to schedule on Windows nodes
  README.md
  webhook/README.md
  webhook/deployment.yaml
  webhook/generate-certs.sh
  webhook/namespace.yaml
  webhook/runtimeclass.yaml
  webhook/setup.sh
Labels: size/XL, lgtm, cncf-cla: yes, approved

#97 fix windows worker number
  terraform/jumper/main.tf
Labels: size/XS, lgtm, cncf-cla: yes, approved

#100 Terraform modules for Amazon EKS cluster refactored
  .gitignore
  terraform/.gitignore
  terraform/aws/eks-windows/README.md
  terraform/aws/eks-windows/locals.tf
  terraform/aws/eks-windows/main.tf
  terraform/aws/eks-windows/outputs.tf
  terraform/aws/eks-windows/variables.tf
  terraform/aws/vpc/locals.tf
  terraform/aws/vpc/main.tf
  terraform/aws/vpc/output.tf
  terraform/aws/vpc/variable.tf
  terraform/data.tf
  terraform/locals.tf
  terraform/main.tf
  terraform/provider.tf
  terraform/terraform.tf
  terraform/variables.tf
Labels: size/XL, lgtm, cncf-cla: yes, ok-to-test, approved
