Repository kubernetes-sigs/windows-operational-readiness, pull requests merged in 2023-12, with the labels that each got.

#102 Remove failing scheduling tests
  specifications/core-scheduling/spec.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#103 Fixing Makefile targets rename for staging
  Makefile
Labels: kind/bug, size/XS, lgtm, cncf-cla: yes, approved

#104 Adding reporter command line
  .github/workflows/tests.yml
  Makefile
  cmd/reporter.go
  cmd/root.go
  go.mod
  go.sum
  hack/build_k8s_test_binary.sh
  pkg/report/clean.go
  pkg/report/parse.go
  pkg/report/types.go
  pkg/testcases/cases.go
  pkg/testcases/context_test.go
  tests/samples/junit_1101_fail.xml
  tests/samples/junit_1101_valid.xml
  tests/testcases/context.go
  tests/windows_operational_readiness_suite_test.go
  tests/xml/xml.go
Labels: kind/feature, size/XL, lgtm, cncf-cla: yes, sig/windows, approved

#105 Update README.md
  README.md
Labels: size/XS, cncf-cla: yes, approved
