Repository kubernetes-sigs/windows-operational-readiness, pull requests merged in 2023-07, with the labels that each got.

#76 Update the README.md
  Makefile
  README.md
  cmd/root.go
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#77 Add GitHub issue and Pull request templates
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, cncf-cla: yes, size/M, needs-ok-to-test, approved

#79 Fix `make clean` as `--report-prefix/` is recognized as option
  Makefile
Labels: size/XS, cncf-cla: yes, needs-ok-to-test, approved

#80 Add ginkgo verbose logging for e2e tests
  README.md
  cmd/root.go
  pkg/testcases/cases.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#82 Fix previous commit causing unit test failures
  pkg/testcases/cases.go
  pkg/testcases/context.go
Labels: size/XS, cncf-cla: yes
