Repository kubernetes-sigs/windows-operational-readiness, pull requests merged in 2023-09, with the labels that each got.

#88 Bump up Golang and various dependencies
  .github/workflows/golangci-lint.yml
  .github/workflows/unit-tests.yml
  exp/Makefile
  exp/go.mod
  exp/go.sum
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, ok-to-test

#89 Update test cases for Core.Scheduling and Core.Concurrent
  cmd/root.go
  specifications/core-concurrent/spec.yaml
  specifications/core-scheduling/spec.yaml
Labels: cncf-cla: yes, size/M

#81 Add new owners
  OWNERS
Labels: size/XS, cncf-cla: yes, needs-ok-to-test

#92 AWS: Create a jumper
  hack/aws-jumper.sh
Labels: cncf-cla: yes, size/M

#93 AWS: setup configuration for a bastion
  terraform/jumper/.terraform.lock.hcl
  terraform/jumper/README.md
  terraform/jumper/data.tf
  terraform/jumper/locals.tf
  terraform/jumper/main.tf
  terraform/jumper/provider.tf
  terraform/jumper/versions.tf
Labels: lgtm, cncf-cla: yes, size/L, approved
