Repository kubernetes-sigs/windows-operational-readiness, pull requests merged in 2024-01, with the labels that each got.

#106 Fixing table format on a method and ascii table, CSV output is available
  cmd/reporter.go
  go.mod
  go.sum
  pkg/report/render.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#107 Parallel reading of pipes and strerr read
  pkg/testcases/cases.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#108 Add ability skip cloud provider
  .gitignore
  README.md
  assets/images/reporter_example.png
  cmd/root.go
  pkg/testcases/cases.go
Labels: lgtm, cncf-cla: yes, size/M, approved
